services:
  # Main FastAPI application
  sentiment_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8001:8000"
    env_file:
      - .env
    environment:
      - NATS_HOSTS=nats://nats:4222
    volumes:
      - .:/app
    depends_on:
      - sentiment_service_migrations
      - nats
    networks:
      - bf_service_network

  sentiment_service_migrations:
    image: sentiment_service:latest
    command: ["uv", "run", "alembic",  "upgrade", "head"]
    env_file:
      - .env
    volumes:
      - ./migrations:/app/migrations
      - ./alembic.ini:/app/alembic.ini
    depends_on:
      - sentiment_service_postgres
    networks:
      - sentiment_service_network

  # DB service
  sentiment_service_postgres:
    image: postgres:16-alpine
    env_file:
      - .env
    environment:
      - PGPORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:${POSTGRES_PORT}"
    volumes:
      - sentiment_service_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - sentiment_service_network
    restart: unless-stopped

  nats:
    image: nats:latest
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"  # NATS client port
      - "8222:8222"  # NATS monitoring port
    networks:
      - sentiment_service_network
    restart: unless-stopped


volumes:
  sentiment_service_postgres_data:

networks:
  sentiment_service_network:
    name: sentiment_service_network
    external: true
